databases:
  - name: appBotica
    databaseName: appBotica
    user: appBotica

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars: 
      - key: DATABASE_URL
        fromDatabase:
          name: appBotica
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
