databases:
  - name: appBotica
    ipAllowList: []

services:
  - type: web
    name: Botica-app 
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exc rails s
    envVars: 
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: appBotica
          property: connectionString
      - type: redis
        name: redis
        ipAllowList: []
        plan: free
        maxmemoryPolicy: noeviction 

